/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 38
#define YY_END_OF_BUFFER 39
static yyconst short int yy_accept[265] =
    {   0,
       36,   36,   39,   37,   38,   36,   37,   35,   37,   29,
       32,   26,   31,   34,   31,   37,   37,   37,   14,   14,
       28,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   30,   37,   36,   31,    0,   33,    0,    0,    0,
        0,   26,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   17,    0,    0,    0,    0,    3,    0,
        0,    0,    0,    0,    0,    0,   16,    0,    0,   26,
        0,   23,    0,   27,    0,    0,    0,    0,   24,    0,
        0,    0,    0,    2,    0,    1,    0,    0,    0,    0,
       12,    0,    0,    7,    0,    0,    0,   22,    0,    0,

        0,    0,    0,   13,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    8,    0,    0,   23,   23,   21,    0,    0,
        0,    0,    0,   25,    0,   19,   19,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   27,    6,    0,
        0,    5,   22,   22,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   27,   27,    9,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       19,    0,    0,   11,   27,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   10,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   20,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   18,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    1,    6,    1,    7,
        8,    9,    9,   10,    9,   11,    9,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    1,   13,
       14,   15,    1,    1,   16,   16,   16,   16,   16,   17,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   18,   16,   16,   16,   16,   16,   16,
       19,    1,   20,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   23,   28,   29,   23,   23,   30,   31,   32,
       33,   23,   23,   34,   35,   36,   37,   23,   38,   23,
       23,   23,   39,   40,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    3,    1,    1,
        1,    4,    1,    5,    1,    6,    6,    6,    7,    7,
        8,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    1,    1,
        1
    } ;

static yyconst short int yy_base[302] =
    {   0,
        0,    0,  608,  787,  787,   39,  593,   40,  600,  787,
      787,   43,  589,  588,  586,  576,   29,   31,   50,  787,
      787,  575,   38,   42,   40,   52,   43,   53,   54,   61,
       60,  787,  554,   87,  787,   88,  787,   83,  578,  583,
      576,    0,   93,  572,   94,  542,  558,    0,   79,   64,
       92,  557,  564,  787,  100,   90,   92,   93,  112,   95,
       97,  102,  107,  103,  111,  109,  787,  132,  144,  561,
      145,  130,  148,  167,  131,  137,  172,  560,  787,    0,
      175,  143,  131,  547,  157,   50,  185,  553,  541,  168,
      537,  146,  175,  534,  170,  133,  194,  190,  205,  542,

        0,  197,  177,  532,  208,  204,  205,  216,  540,  212,
        0,  228,  217,  231,    0,  250,  218,  516,  214,  529,
      217,  197,  526,  534,    0,  533,    0,  787,  235,  258,
      237,  238,  254,  787,  257,  266,  269,  523,  264,  529,
      536,  529,  275,  526,  279,  499,    0,  512,  516,  501,
      147,  278,  523,    0,  289,  522,    0,  283,  505,    0,
      293,  301,  516,  305,  303,  313,  332,  484,  493,  497,
      317,  493,  318,  321,  331,  337,  490,  345,  341,  353,
      787,  473,    0,    0,  431,  372,  288,  356,  454,  320,
      447,    0,  343,  450,    0,  355,  442,  442,  435,  357,

      425,  376,  388,    0,  410,  291,  787,  381,  386,  356,
      419,  392,  396,  408,  397,  418,  428,  448,  406,  405,
      404,  393,  429,  389,  432,  356,    0,  452,  361,    0,
      433,  457,  468,  787,  358,    0,  467,  471,  342,  472,
      479,  489,  508,  490,  496,  372,  331,    0,  470,  260,
      504,  488,  512,  248,    0,  517,  233,  192,    0,  518,
      157,  519,   70,  787,  547,  551,  557,  565,  571,  575,
      581,  589,  595,  603,  609,  615,  622,  628,  632,  638,
      646,  652,  658,  664,  672,  678,  684,  690,  697,  703,
      711,  717,  725,  733,  739,  745,  751,  759,  765,  771,

      777
    } ;

static yyconst short int yy_def[302] =
    {   0,
      264,    1,  264,  264,  264,  264,  264,  265,  264,  264,
      264,  264,  264,  264,  264,  266,  266,  266,  267,  264,
      264,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  264,  264,  264,  264,  265,  264,   12,  264,  264,
      264,   12,  268,  264,  268,  264,  266,  269,  266,  266,
      264,  270,  271,  264,  270,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  264,  268,  272,   38,
      268,  264,  268,  269,  266,  266,  270,  264,  264,  273,
      264,  271,  274,  266,  266,  266,  264,  275,  266,  266,
      266,  266,  266,  266,  266,  266,  272,  264,  272,  264,

      276,  277,  266,  266,  270,  264,  273,  271,  264,  264,
      278,  274,  264,  266,  279,  264,  275,  269,  266,  266,
      266,  266,  266,  264,  280,  264,  276,  264,  264,  277,
      271,  264,  264,  264,  278,  264,  264,  279,  116,  264,
      264,  264,  281,  264,  281,  264,  282,   74,  266,  269,
      266,  266,  264,  280,  277,  264,  283,  264,  264,  284,
      281,  285,  139,  281,  264,  281,  282,   74,   74,  266,
      264,  286,  277,  264,  283,  264,  284,  285,  264,  285,
      264,  264,  287,   74,   74,  264,  286,  264,  288,  289,
      264,  290,  264,  287,   74,  186,  264,  264,  264,  291,

      264,  291,  264,  292,  264,  288,  264,  264,  289,  264,
      290,  291,  293,  196,  291,  264,  291,  292,  205,  264,
      264,  264,  294,  264,  294,  264,  295,  289,  264,  296,
      293,  264,  293,  264,  264,  297,  294,  298,  219,  294,
      264,  294,  295,  289,  264,  296,  264,  299,  264,  297,
      298,  264,  298,  264,  300,  264,  299,  264,  301,  264,
      300,  264,  301,    0,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264
    } ;

static yyconst short int yy_nxt[829] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   10,   11,    4,
        4,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   22,   23,   22,   24,   25,   22,   26,   22,
       27,   28,   22,   29,   30,   22,   22,   31,   32,   33,
       32,   34,   34,   34,   34,   38,   39,   38,   40,   48,
       49,   48,  115,   41,   42,   43,   44,   45,   48,   56,
       48,   51,   48,   48,   50,   52,   52,   52,   53,   54,
       48,   57,   48,   48,   48,   61,   58,  181,   59,   63,
       48,   48,   46,   60,   48,   62,   64,   65,   66,   34,
      264,   34,   67,  264,  264,   71,   71,   71,   71,   48,

       76,   77,   78,   51,   72,   72,   68,   68,   75,   83,
       48,   79,   48,   48,   87,   48,   87,   48,   88,   54,
       80,   90,   48,   48,   86,   84,   85,   48,   92,   48,
       89,   48,   48,  112,   71,  112,   71,   91,   94,   95,
      100,   72,   93,   72,   96,  264,   97,   71,   97,   71,
      264,   48,  264,   48,  264,   98,   72,   48,  264,  264,
      123,  264,  104,  111,  181,  103,   48,   48,  101,   38,
       39,   38,   40,  102,  105,  120,  105,   48,  170,   43,
       44,   45,  114,   51,  108,  109,   81,   87,   48,   87,
       48,   88,  264,  119,  110,   48,   97,   48,   97,  122,

      124,   98,  104,  262,  128,   98,   46,  264,  129,  264,
      105,  121,  105,   77,   77,  106,  264,   48,  131,   51,
      131,  133,  152,   79,   79,  125,   83,   81,  264,  264,
      112,  134,  112,  136,   48,  137,   54,   48,  147,  131,
      234,  131,  128,  149,  155,  156,  129,  108,   81,  132,
      151,   48,  139,  140,  139,  141,  158,  110,  158,  260,
      142,  116,  143,  144,  145,  264,  108,  234,  137,  264,
      137,  137,   53,  137,  264,  264,  110,  164,  157,  164,
      171,  164,  171,  164,  172,  158,  165,  158,  161,  146,
      165,  173,  161,  173,  159,  164,  264,  164,   48,  264,

      129,   53,  264,  178,  165,  178,  264,  164,  204,  164,
      181,  227,  179,  182,  165,  264,  165,  264,  264,  171,
      173,  171,  173,  172,  264,  264,  264,  207,  128,  129,
      155,  208,  174,  183,  139,  140,  139,  141,  128,  188,
      155,  188,  256,  189,  143,  144,  145,  178,  181,  178,
      181,  191,  179,  239,  193,  264,  179,  264,  188,  215,
      188,  215,  189,  181,  264,  264,  264,  210,  216,  249,
      212,  146,  245,  192,  196,  197,  196,  198,  215,  207,
      215,  228,  199,  186,  200,  201,  202,  216,  207,  212,
      228,  229,  208,  264,  215,  238,  215,  264,  231,  215,

      231,  215,  237,  216,  239,  264,  230,  232,  216,  238,
      264,  203,  219,  220,  219,  221,  264,  264,  237,  214,
      222,  205,  223,  224,  225,  234,  181,  213,  235,  216,
      264,  240,  264,  240,  240,  231,  240,  231,  212,  264,
      241,  264,  237,  241,  232,  237,  214,  213,  236,  226,
      196,  197,  196,  198,  244,  212,  244,  181,  210,  264,
      200,  201,  202,  208,  234,  205,  195,  247,  232,  240,
      264,  240,  264,  251,  240,  251,  240,  234,  241,  264,
      264,  249,  252,  241,  193,  264,  181,  203,  248,  254,
      241,  264,  244,  264,  244,  181,  190,  264,  258,  252,

      264,  208,  264,  207,  186,  228,  251,  245,  251,  255,
      219,  220,  219,  221,  264,  252,  264,   48,  185,  184,
      223,  224,  225,  264,  234,  181,  181,  163,  256,  260,
      262,  176,  259,  174,  153,  169,   48,  168,  162,  161,
      163,  162,  161,  160,  126,  153,   48,  226,   36,  150,
      148,  132,   48,  126,   48,   36,   47,   48,   47,   47,
       55,  118,   55,   55,  116,   55,   73,   48,   73,   73,
       73,  106,   70,   73,   74,   81,   74,   80,   48,   74,
       52,   69,   52,   52,   82,   68,   82,   70,   69,   82,
       99,   68,   99,   37,   99,   48,   48,   99,  107,   35,

      107,   35,   35,  107,  113,   37,   35,  264,  264,  264,
      264,  113,  117,  264,  117,  264,  264,  117,  127,  264,
      127,  264,  264,  127,  130,  130,  264,  130,  264,  264,
      130,  135,  264,  135,  264,  264,  135,  138,  264,  264,
      138,  154,  264,  154,  264,  264,  154,  166,  264,  166,
      166,  166,  264,  264,  166,  167,  264,  167,  264,  264,
      167,  175,  264,  175,  264,  264,  175,  177,  264,  177,
      264,  264,  177,  180,  264,  180,  264,  180,  264,  264,
      180,  187,  264,  187,  264,  264,  187,  194,  264,  194,
      264,  264,  194,  206,  264,  206,  264,  264,  206,  209,

      209,  264,  209,  264,  264,  209,  211,  264,  211,  264,
      264,  211,  217,  264,  217,  217,  217,  264,  264,  217,
      218,  264,  218,  264,  264,  218,  233,  264,  233,  264,
      233,  264,  264,  233,  242,  264,  242,  242,  242,  264,
      264,  242,  243,  264,  243,  264,  264,  243,  246,  264,
      246,  264,  264,  246,  250,  264,  250,  264,  264,  250,
      253,  264,  253,  264,  253,  264,  264,  253,  257,  264,
      257,  264,  264,  257,  261,  264,  261,  264,  264,  261,
      263,  264,  263,  264,  264,  263,    3,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264
    } ;

static yyconst short int yy_chk[829] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    8,    6,    8,   12,   12,   12,   12,   17,
       17,   18,   86,   12,   12,   12,   12,   12,   23,   23,
       25,   19,   24,   27,   18,   19,   19,   19,   19,   19,
       86,   24,   26,   28,   29,   27,   25,  263,   26,   29,
       31,   30,   12,   26,   50,   28,   30,   31,   31,   34,
       36,   34,   36,   38,   38,   43,   45,   43,   45,   49,

       50,   51,   51,   51,   43,   45,   43,   45,   49,   55,
       56,   51,   57,   58,   59,   60,   59,   61,   59,   55,
       55,   61,   62,   64,   58,   56,   57,   63,   63,   66,
       60,   65,   59,   83,   68,   83,   68,   62,   64,   65,
       72,   72,   63,   68,   66,   68,   69,   71,   69,   71,
       73,   75,   73,   96,   82,   69,   71,   76,   71,   73,
       96,   73,   76,   82,  261,   75,   92,  151,   73,   74,
       74,   74,   74,   74,   77,   92,   77,   85,  151,   74,
       74,   74,   85,   77,   81,   81,   81,   87,   90,   87,
       95,   87,   77,   90,   81,   93,   97,  103,   97,   95,

       98,   98,  103,  258,  102,   97,   74,   99,  102,   99,
      105,   93,  105,  106,  107,  106,   99,  122,  108,  105,
      108,  110,  122,  106,  107,   99,  113,  108,  105,  117,
      112,  110,  112,  114,  119,  114,  113,  121,  117,  131,
      257,  131,  129,  119,  129,  129,  129,  132,  131,  132,
      121,  114,  116,  116,  116,  116,  133,  132,  133,  254,
      116,  116,  116,  116,  116,  130,  135,  250,  136,  130,
      136,  137,  133,  137,  139,  139,  135,  143,  130,  143,
      152,  145,  152,  145,  152,  158,  143,  158,  143,  116,
      145,  155,  145,  155,  136,  161,  155,  161,  152,  187,

      155,  158,  206,  162,  161,  162,  161,  164,  187,  164,
      165,  206,  162,  165,  165,  166,  164,  166,  164,  171,
      173,  171,  173,  171,  166,  173,  166,  190,  174,  173,
      174,  190,  174,  166,  167,  167,  167,  167,  175,  176,
      175,  176,  247,  176,  167,  167,  167,  178,  179,  178,
      193,  179,  179,  239,  193,  180,  178,  180,  188,  200,
      188,  200,  188,  210,  180,  196,  196,  210,  200,  235,
      200,  167,  229,  180,  186,  186,  186,  186,  202,  246,
      202,  246,  186,  186,  186,  186,  186,  202,  208,  202,
      208,  208,  208,  209,  212,  226,  212,  209,  213,  215,

      213,  215,  224,  212,  222,  212,  209,  213,  215,  221,
      215,  186,  205,  205,  205,  205,  219,  219,  220,  214,
      205,  205,  205,  205,  205,  216,  211,  203,  216,  216,
      217,  223,  217,  223,  225,  231,  225,  231,  201,  217,
      223,  217,  223,  225,  231,  225,  199,  198,  217,  205,
      218,  218,  218,  218,  228,  197,  228,  194,  191,  228,
      218,  218,  218,  228,  232,  189,  185,  232,  232,  237,
      233,  237,  233,  238,  240,  238,  240,  249,  237,  233,
      237,  249,  238,  240,  182,  240,  241,  218,  233,  241,
      241,  242,  244,  242,  244,  252,  177,  244,  252,  252,

      242,  244,  242,  245,  172,  245,  251,  245,  251,  242,
      243,  243,  243,  243,  253,  251,  253,  170,  169,  168,
      243,  243,  243,  253,  256,  260,  262,  163,  256,  260,
      262,  159,  253,  156,  153,  150,  149,  148,  146,  144,
      142,  141,  140,  138,  126,  124,  123,  243,  265,  120,
      118,  109,  104,  100,   94,  265,  266,   91,  266,  266,
      267,   89,  267,  267,   88,  267,  268,   84,  268,  268,
      268,   78,   70,  268,  269,   53,  269,   52,   47,  269,
      270,   46,  270,  270,  271,   44,  271,   41,   40,  271,
      272,   39,  272,   33,  272,   22,   16,  272,  273,   15,

      273,   14,   13,  273,  274,    9,    7,    3,    0,    0,
        0,  274,  275,    0,  275,    0,    0,  275,  276,    0,
      276,    0,    0,  276,  277,  277,    0,  277,    0,    0,
      277,  278,    0,  278,    0,    0,  278,  279,    0,    0,
      279,  280,    0,  280,    0,    0,  280,  281,    0,  281,
      281,  281,    0,    0,  281,  282,    0,  282,    0,    0,
      282,  283,    0,  283,    0,    0,  283,  284,    0,  284,
        0,    0,  284,  285,    0,  285,    0,  285,    0,    0,
      285,  286,    0,  286,    0,    0,  286,  287,    0,  287,
        0,    0,  287,  288,    0,  288,    0,    0,  288,  289,

      289,    0,  289,    0,    0,  289,  290,    0,  290,    0,
        0,  290,  291,    0,  291,  291,  291,    0,    0,  291,
      292,    0,  292,    0,    0,  292,  293,    0,  293,    0,
      293,    0,    0,  293,  294,    0,  294,  294,  294,    0,
        0,  294,  295,    0,  295,    0,    0,  295,  296,    0,
      296,    0,    0,  296,  297,    0,  297,    0,    0,  297,
      298,    0,  298,    0,  298,    0,    0,  298,  299,    0,
      299,    0,    0,  299,  300,    0,  300,    0,    0,  300,
      301,    0,  301,    0,    0,  301,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analizador.l"
#define INITIAL 0
#line 2 "analizador.l"

#define yywrap() 1
#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <string.h>
FILE *yyin;

void print(char *value, char *category);

/* KEYWORDS */
/*ALLOCATION              {VARIABLE}{space}={space}{data_type} */
#line 654 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 65 "analizador.l"

#line 807 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 265 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 787 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "analizador.l"
{
    print(yytext, "FUN_KEYWORD");
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 70 "analizador.l"
{
    print(yytext, "CAT_KEYWORD");
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 74 "analizador.l"
{
    print(yytext, "IF_KEYWORD");
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "analizador.l"
{
    print(yytext, "ELSE_KEYWORD");
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 82 "analizador.l"
{
    print(yytext, "WHILE_KEYWORD");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 86 "analizador.l"
{
    print(yytext, "IF_KEYWORD");
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 90 "analizador.l"
{
    print(yytext, "SET_KEYWORD");
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "analizador.l"
{
    print(yytext, "WITH_KEYWORD");
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "analizador.l"
{
    print(yytext, "RETURN_KEYWORD");
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 102 "analizador.l"
{
    print(yytext, "REAL_SET_KEYWORD");
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "analizador.l"
{
    print(yytext, "INT_SET_KEYWORD");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "analizador.l"
{
    print(yytext, "NOT_KEYWORD");
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 114 "analizador.l"
{
    print(yytext, "BOOLEAN");
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 118 "analizador.l"
{
    print(yytext, "ARRAY_SYMBOL");
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 122 "analizador.l"
{
    print(yytext, "SYMBOL");
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 126 "analizador.l"
{
    print(yytext, "SYMBOL_CHAIN");
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 130 "analizador.l"
{
    print(yytext, "CATEGORY_ALPHABET");
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 134 "analizador.l"
{
    print(yytext, "ITERATION");
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 138 "analizador.l"
{
    print(yytext, "CONTROL");
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 142 "analizador.l"
{
    print(yytext, "FUNCTION");
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 146 "analizador.l"
{
    print(yytext, "FUNCTION_CALL");
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 150 "analizador.l"
{
    print(yytext, "LOGICAL_OPERATION");
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 154 "analizador.l"
{
    print(yytext, "COMPARISON_OPERATION");
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 158 "analizador.l"
{
    print(yytext,"ARRAY");
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 162 "analizador.l"
{
    print(yytext,"MATRIX");
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 166 "analizador.l"
{
    print(yytext,"NUMBER");
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 170 "analizador.l"
{
    print(yytext,"VARIABLE");
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 174 "analizador.l"
{
    print(yytext, "VARIABLE_MID_SYMBOL");
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 178 "analizador.l"
{
    print(yytext,"GROUP");
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 182 "analizador.l"
{
    print(yytext,"BLOCK");
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 186 "analizador.l"
{
    print(yytext,"COMPARISON_OPERATOR");
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 190 "analizador.l"
{
    print(yytext,"ARITHMETIC_OPERATOR");
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 194 "analizador.l"
{
    print(yytext,"LOGICAL_OPERATOR");
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 198 "analizador.l"
{
    print(yytext,"ASSIGNMENT_OPERATOR");
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 202 "analizador.l"
{
    print(yytext,"CHAIN");
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 206 "analizador.l"
{

}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 210 "analizador.l"
{
    printf("\nCaracter invalido: %s", yytext);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 214 "analizador.l"
ECHO;
	YY_BREAK
#line 1154 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 265 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 265 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 264);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 214 "analizador.l"

/*
int main()
{
    yylex();
}
*/
int main (int argc, char *argv[]){
    argv[1] = "test01.txt";
    if ((yyin = fopen(argv[1], "rt")) == NULL) {
        printf("\nNo se pudo leer el archivo: %s\n", argv[1]);
        return 1;
    } else {
        printf("\nEl archivo %s se abrio correctamente\n", argv[1]);
        yylex();
    }
    printf("\nLectura finalizada.");
    fclose(yyin);
    return 0;
}
 
//function that recives the lexical category and its value and prints it
void print(char *value, char *category)
{   
    printf("\n( %s , %s ) ", value, category );
}