/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 20
#define YY_END_OF_BUFFER 21
static yyconst short int yy_accept[250] =
    {   0,
        0,    0,   21,   20,   20,   20,   20,   13,   16,   10,
       15,   18,   15,   12,   20,   12,   12,   12,   12,   12,
       12,   12,   12,   14,   20,   15,   19,    0,   17,    0,
        0,    0,    0,   10,    0,    0,    0,    0,    0,    0,
       12,    0,    0,    0,    0,   12,   12,   12,   11,   12,
       12,   12,   12,   12,    0,    0,   10,    0,    7,    7,
        5,    0,    0,    0,    3,    3,    0,    0,    0,    8,
        0,    0,    0,   11,   12,   11,    0,    0,   12,   12,
       12,   12,    0,    6,    6,    0,    7,    0,    0,    0,
        0,    3,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    2,    0,    0,    0,    0,   12,   12,   12,    0,
        6,    7,    0,    0,    3,    0,    0,    3,    0,    0,
        0,    0,    0,    0,    9,    2,    2,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   11,
       12,   11,    6,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    4,    0,    0,
        0,    0,    0,    0,    2,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    4,    1,    1,    1,    5,    1,    6,
        7,    8,    8,    9,    8,   10,    8,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,   12,
       13,   14,    1,    1,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       16,    1,   17,    1,    1,    1,   18,   19,   20,   21,

       22,   23,   19,   24,   25,   19,   19,   26,   27,   28,
       29,   19,   19,   30,   31,   32,   33,   19,   34,   19,
       19,   19,   35,   36,   37,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[38] =
    {   0,
        1,    2,    3,    4,    3,    5,    6,    1,    7,    1,
        8,    3,    9,    3,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,    1,    3,    1
    } ;

static yyconst short int yy_base[294] =
    {   0,
        0,    0,  620, 1128,  606,  614,  612, 1128, 1128,   36,
      603,  602,  601,   71,   40,  106,   26,   24,   35,   25,
       37,   42,   43, 1128,  577, 1128, 1128,  608, 1128,   52,
      598,  605,  598,    0,   67,  595,   77,  571,   85,   59,
      588,   89,   86,   77,  589,   74,   83,   95,  123,  110,
       98,  103,   97,  108,  132,  135,  588,  145,  122,    0,
     1128,  141,  146,  155,  150,    0,   88,  161,  587, 1128,
      145,  164,  161,  579,  158,  165,  180,  178,  169,  146,
      170,  120,  188,  183,    0,  580,    0,  193,  579,  194,
      578,    0,  196,  193,  577,  207,  203,  213,  576,  199,

      210,  224,  241,  575,  276,  311,  203,  204,  213,  574,
        0,  573,  245,  229,  572,  246,  571, 1128,  216,  249,
      252,  228,  254,  266, 1128,  270,  556,  574,  287,  346,
      265,  566,  573,  566,  289,  563,  297,  539,  381,  556,
      223,  301,  562,  324,  300,  325,  561,  275,  313,  329,
      548,  327,  561,  555,  416,  342,  350,  331,  360,  356,
      557,  366,  332,  376,  380,  394,  373, 1128,  392,  297,
      551,  402,  398,  549, 1128,  543,  533,  520,  451,  486,
      410,  421,  518,  429,  506,  367,  505,  508,  358,  428,
      521,  346,  501,  502,  495,  430,  484,  446,  460,  556,

      591,  626,  440,  459,  400,  468,  661,  465,  469,  405,
      470,  475,  442,  435,  411,  417,  389,  490,  379,  500,
      345,  696,  326,  473,  498,  325, 1128,  310,  266,  508,
      516,  256,  526,  531,  257,  226,  191,  525,  541,  537,
      162,  106,   75,  539,   54,   38,  542,  544, 1128,  729,
      741,  747,  759,  767,  779,  786,  792,  804,  810,  818,
      824,  830,  837,  845,  851,  858,  864,  876,  882,  894,
      901,  910,  922,  934,  942,  954,  962,  970,  978,  986,
      992, 1004, 1010, 1022, 1034, 1046, 1058, 1066, 1078, 1086,
     1098, 1106, 1114

    } ;

static yyconst short int yy_def[294] =
    {   0,
      249,    1,  249,  249,  249,  250,  249,  249,  249,  249,
      249,  249,  249,  251,  252,  251,   16,   16,   16,   16,
       16,   16,   16,  249,  249,  249,  249,  250,  249,   10,
      249,  249,  249,   10,  253,  249,  253,  249,   30,  254,
       16,  255,  249,  256,  257,   16,   16,   16,   16,   16,
       16,   16,   16,   16,  253,  258,   30,  253,  249,  259,
      249,  249,  260,  255,  249,  261,  262,  252,  249,  249,
      256,  249,  263,   16,   16,   16,   39,  264,   16,   16,
       16,   16,  258,  249,  265,  249,  259,  254,  249,  260,
      249,  261,  249,  266,  267,  252,  249,  257,  249,  249,

      263,   16,  268,  269,  249,  270,   16,   16,   16,  249,
      265,  249,  254,  249,  249,  262,  249,  249,  266,  249,
      271,  257,  249,  249,  249,   39,  126,  272,  105,  273,
      129,  249,  249,  249,  274,  249,  274,  249,  270,   16,
       16,   16,  249,  262,  249,  267,  249,  249,  271,  249,
      249,  275,  272,  249,  273,  274,  276,  105,  274,  249,
      277,   39,  278,  267,  249,  249,  249,  249,  249,  279,
      131,  276,  249,  280,  249,  249,  277,  281,  249,  282,
      249,  249,  283,  275,  249,  279,  249,  280,  249,  179,
      284,  190,  249,  249,  249,  285,  249,  285,  249,  282,

      249,  286,  275,  249,  249,  249,  284,  285,  287,  179,
      285,  249,  288,  201,  249,  249,  249,  289,  249,  289,
      249,  286,  192,  287,  249,  290,  249,  249,  288,  289,
      291,  214,  289,  249,  292,  249,  290,  249,  291,  249,
      293,  249,  292,  249,  249,  293,  249,  249,    0,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249

    } ;

static yyconst short int yy_nxt[1166] =
    {   0,
        4,    4,    5,    6,    7,    8,    8,    9,    4,    4,
       10,   11,   12,   13,   14,   15,    4,   14,   14,   16,
       14,   17,   18,   14,   19,   14,   20,   14,   14,   21,
       22,   14,   14,   23,   24,   25,   24,   30,   31,   30,
       32,   41,   41,   41,  175,   33,   34,   35,   36,   37,
       43,   47,   41,   50,   41,   45,   48,   49,   51,   41,
       41,  249,  249,   52,  248,   61,   53,   54,   58,   62,
       58,   38,   39,   31,   39,   32,   40,   59,   58,   55,
       58,  175,   35,   42,   37,   68,   39,   59,   39,   55,
       64,   41,   64,   70,   68,   69,   43,   42,   93,   65,

       41,   55,   70,   95,   67,   74,   38,   39,   31,   39,
       32,   40,   41,   75,   41,   41,  247,   35,   42,   37,
       41,   81,   76,   46,   77,   41,   77,   41,   78,   80,
       79,   86,   59,   58,   74,   58,   83,   41,   83,   82,
       41,   38,   59,   74,  249,   84,   58,   61,   58,   88,
       89,   62,   61,   68,   88,   59,   64,  249,   64,   91,
       65,   70,   96,   41,   96,   65,  103,  249,  175,   98,
       67,   43,   98,   99,   72,   41,  249,  100,  108,  102,
      100,   77,   41,   77,   61,  104,   41,   41,  105,   83,
      107,   83,  110,   84,  113,  109,  113,  227,   84,  249,

       61,  116,   88,   62,  116,  117,   93,  124,   96,  118,
       96,   68,  118,   97,  122,  125,  122,   43,   98,   70,
       41,   41,  249,   72,  116,  126,  100,  127,  140,  122,
       41,  122,  118,  141,  142,   61,  244,   88,   72,  114,
       41,   41,   39,   31,   39,   32,  113,  144,  113,  144,
       74,  249,   35,   42,   37,   62,   93,  146,  147,  120,
      146,  249,   98,  175,  123,  148,  232,  150,  148,  150,
      100,  127,  227,  127,  249,  249,   38,  131,  132,  131,
      133,   45,   61,  166,   88,  134,  105,  135,  136,  137,
      159,  118,  159,  249,  151,  249,  154,  129,  159,  160,

      159,  156,  162,  168,  162,  184,  163,  160,  116,  156,
      145,  138,  131,  132,  131,  133,  118,   61,   41,   88,
      238,  146,  135,  136,  137,  144,  164,  144,  164,  148,
      150,  227,  150,  168,   93,  120,  223,  169,   61,  249,
      249,  158,  179,  159,   45,  159,  138,  131,  132,  131,
      133,  172,  160,  172,  249,  249,  249,  135,  136,  137,
      173,  159,  175,  159,  175,  176,  160,  162,  189,  162,
      160,  178,  249,  168,  182,  184,  182,  164,  183,  164,
      231,  138,  131,  132,  131,  133,  120,   61,  146,   88,
      165,  230,  135,  136,  137,  181,  148,  181,  168,  232,

      184,  185,  169,  172,  175,  172,  175,  187,  173,   95,
      205,  181,  173,  181,  249,  210,  138,  131,  132,  131,
      133,  231,  182,  230,  182,   95,  183,  135,  136,  137,
      203,  211,  203,  211,  249,  249,  249,  206,  190,  169,
      212,  203,  208,  203,  249,  249,  249,  211,  227,  211,
      169,  138,  192,  193,  192,  194,  212,   61,  208,   88,
      195,  179,  196,  197,  198,  168,  211,  184,  211,  204,
      224,  211,  224,  211,  224,  212,  224,  249,  223,  225,
      212,  227,  249,  225,  228,  212,  199,  192,  193,  192,
      194,  233,   61,  233,   88,  209,  208,  196,  197,  198,

      234,  233,  230,  233,  227,  210,  209,  236,  225,  233,
      234,  233,  230,  208,  175,  205,  204,  239,  234,  239,
      249,  199,  192,  193,  192,  194,  240,  233,  201,  233,
      190,  227,  196,  197,  198,  238,  234,  175,  249,  175,
      242,  234,  239,  175,  239,  227,  245,  240,  175,  244,
      175,  240,  247,  189,  248,  175,  199,  192,  193,  192,
      194,  171,   61,  175,   88,  171,  152,  196,  197,  198,
      167,  165,  143,   41,  157,  156,  158,  157,  156,  152,
      249,  145,  115,  112,  143,  129,  123,  120,  115,  114,
      112,  199,  214,  215,  214,  216,   41,   97,   57,   72,

      217,  201,  218,  219,  220,   41,   56,   55,   57,   56,
       55,   27,   29,   26,   26,   26,   29,   27,   26,  249,
      249,  249,  249,  249,  249,  249,  221,  214,  215,  214,
      216,  249,  249,  249,  249,  249,  249,  218,  219,  220,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  221,  192,  193,  192,  194,  249,  249,  249,  249,
      249,  249,  196,  197,  198,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  199,  214,  215,  214,

      216,  249,  249,  249,  249,  249,  249,  218,  219,  220,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  221,   28,  249,  249,  249,  249,  249,  249,  249,
      249,   28,   41,   41,   41,   41,  249,  249,   41,   41,
       41,  249,  249,   41,   44,  249,   44,   44,  249,   44,
       60,  249,   60,  249,  249,  249,   60,   60,   60,  249,
      249,   60,   63,  249,   63,  249,   63,  249,  249,   63,
       66,  249,   66,  249,  249,  249,   66,   66,   66,   66,
      249,   66,   71,   71,  249,   71,  249,   71,   71,   73,

      249,   73,  249,  249,   73,   85,  249,   85,  249,  249,
      249,   85,  249,   85,  249,  249,   85,   87,  249,   87,
      249,  249,   87,   90,   90,   90,  249,   90,  249,  249,
       90,   92,  249,   92,  249,  249,   92,   94,  249,   94,
       94,  249,   94,  101,  101,  249,  101,  249,  101,  101,
      106,  249,  106,  249,  106,  249,  249,  106,  111,  249,
      111,  249,  249,  111,  119,  119,  249,  119,  249,  119,
      119,  121,  249,  121,  249,  249,  121,  128,  128,  128,
      249,  249,  249,  249,  128,  128,  249,  249,  128,  130,
      249,  130,  249,  249,  130,  139,  139,  139,  249,  139,

      139,  139,  139,  139,  249,  249,  139,  149,  149,  249,
      149,  249,  149,  149,  153,  249,  249,  153,  249,  153,
      249,  249,  153,  155,  155,  155,  249,  249,  249,  155,
      155,  155,  249,  249,  155,  161,  249,  161,  249,  249,
      249,  161,  161,  161,  249,  249,  161,  170,  249,  170,
      249,  170,  249,  249,  170,  174,  249,  174,  249,  249,
      249,  174,  249,  174,  249,  249,  174,  177,  249,  177,
      249,  177,  249,  249,  177,  180,  249,  180,  249,  180,
      249,  249,  180,  186,  186,  186,  249,  186,  249,  249,
      186,  188,  249,  188,  249,  188,  249,  249,  188,  191,

      249,  191,  249,  249,  191,  200,  200,  200,  249,  200,
      200,  200,  200,  200,  249,  249,  200,  202,  249,  202,
      249,  249,  202,  207,  207,  207,  249,  249,  249,  207,
      207,  207,  249,  249,  207,  213,  249,  213,  249,  249,
      249,  213,  213,  213,  249,  249,  213,  222,  222,  222,
      249,  249,  249,  222,  222,  222,  249,  249,  222,  226,
      249,  226,  249,  249,  249,  226,  249,  226,  249,  249,
      226,  229,  249,  229,  249,  229,  249,  249,  229,  235,
      249,  235,  249,  249,  249,  235,  235,  235,  249,  249,
      235,  237,  249,  237,  249,  237,  249,  249,  237,  241,

      249,  241,  249,  249,  249,  241,  249,  241,  249,  249,
      241,  243,  249,  243,  249,  243,  249,  249,  243,  246,
      249,  246,  249,  246,  249,  249,  246,    3,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249
    } ;

static yyconst short int yy_chk[1166] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   10,   10,   10,
       10,   18,   20,   17,  246,   10,   10,   10,   10,   10,
       15,   17,   19,   20,   21,   15,   18,   19,   21,   22,
       23,   30,   30,   22,  245,   40,   23,   23,   35,   40,
       35,   10,   14,   14,   14,   14,   14,   35,   37,   35,
       37,  243,   14,   14,   14,   44,   39,   37,   39,   37,
       42,   46,   42,   44,   43,   43,   43,   39,   67,   42,

       47,   42,   43,   67,   42,   46,   14,   16,   16,   16,
       16,   16,   48,   47,   53,   51,  242,   16,   16,   16,
       52,   53,   48,   16,   49,   54,   49,   50,   49,   51,
       50,   59,   59,   55,   52,   55,   56,   82,   56,   54,
       49,   16,   55,   82,   55,   56,   58,   62,   58,   62,
       62,   62,   63,   71,   63,   58,   64,   58,   64,   65,
       65,   71,   68,   80,   68,   64,   76,   64,  241,   73,
       64,   68,   72,   72,   72,   75,   68,   73,   80,   75,
       72,   77,   76,   77,   78,   77,   79,   81,   78,   83,
       79,   83,   84,   84,   88,   81,   88,  237,   83,   88,

       90,   94,   90,   88,   93,   93,   93,  100,   96,   94,
       96,   97,   93,   97,   98,  100,   98,   96,  101,   97,
      107,  108,   96,   98,  119,  102,  101,  102,  107,  122,
      109,  122,  119,  108,  109,  114,  236,  114,  122,  114,
      141,  102,  103,  103,  103,  103,  113,  116,  113,  116,
      141,  113,  103,  103,  103,  113,  116,  120,  120,  120,
      121,  116,  123,  235,  123,  120,  232,  124,  121,  124,
      123,  126,  229,  126,  131,  131,  103,  105,  105,  105,
      105,  124,  105,  148,  105,  105,  105,  105,  105,  105,
      135,  148,  135,  129,  126,  129,  129,  129,  137,  135,

      137,  135,  142,  170,  142,  170,  142,  137,  145,  137,
      145,  105,  106,  106,  106,  106,  145,  106,  142,  106,
      228,  149,  106,  106,  106,  144,  146,  144,  146,  149,
      150,  226,  150,  152,  144,  146,  223,  152,  163,  144,
      158,  158,  163,  156,  150,  156,  106,  130,  130,  130,
      130,  157,  156,  157,  156,  192,  192,  130,  130,  130,
      157,  159,  160,  159,  189,  160,  160,  162,  189,  162,
      159,  162,  159,  186,  167,  186,  167,  164,  167,  164,
      221,  130,  139,  139,  139,  139,  164,  139,  165,  139,
      165,  219,  139,  139,  139,  166,  165,  166,  169,  217,

      169,  169,  169,  172,  173,  172,  205,  173,  173,  166,
      205,  181,  172,  181,  210,  210,  139,  155,  155,  155,
      155,  216,  182,  215,  182,  181,  182,  155,  155,  155,
      184,  196,  184,  196,  190,  184,  190,  190,  190,  184,
      196,  203,  196,  203,  214,  214,  203,  198,  213,  198,
      203,  155,  179,  179,  179,  179,  198,  179,  198,  179,
      179,  179,  179,  179,  179,  204,  208,  204,  208,  204,
      209,  211,  209,  211,  224,  208,  224,  208,  206,  209,
      211,  212,  211,  224,  212,  212,  179,  180,  180,  180,
      180,  218,  180,  218,  180,  199,  197,  180,  180,  180,

      218,  220,  218,  220,  225,  195,  194,  225,  225,  230,
      220,  230,  220,  193,  188,  187,  185,  231,  230,  231,
      230,  180,  191,  191,  191,  191,  231,  233,  183,  233,
      178,  238,  191,  191,  191,  238,  233,  234,  233,  177,
      234,  234,  239,  240,  239,  244,  240,  240,  247,  244,
      248,  239,  247,  176,  248,  174,  191,  200,  200,  200,
      200,  171,  200,  161,  200,  154,  153,  200,  200,  200,
      151,  147,  143,  140,  138,  136,  134,  133,  132,  128,
      127,  117,  115,  112,  110,  104,   99,   95,   91,   89,
       86,  200,  201,  201,  201,  201,   74,   69,   57,   45,

      201,  201,  201,  201,  201,   41,   38,   36,   33,   32,
       31,   28,   25,   13,   12,   11,    7,    6,    5,    3,
        0,    0,    0,    0,    0,    0,  201,  202,  202,  202,
      202,    0,    0,    0,    0,    0,    0,  202,  202,  202,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  202,  207,  207,  207,  207,    0,    0,    0,    0,
        0,    0,  207,  207,  207,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  207,  222,  222,  222,

      222,    0,    0,    0,    0,    0,    0,  222,  222,  222,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  222,  250,    0,    0,    0,    0,    0,    0,    0,
        0,  250,  251,  251,  251,  251,    0,    0,  251,  251,
      251,    0,    0,  251,  252,    0,  252,  252,    0,  252,
      253,    0,  253,    0,    0,    0,  253,  253,  253,    0,
        0,  253,  254,    0,  254,    0,  254,    0,    0,  254,
      255,    0,  255,    0,    0,    0,  255,  255,  255,  255,
        0,  255,  256,  256,    0,  256,    0,  256,  256,  257,

        0,  257,    0,    0,  257,  258,    0,  258,    0,    0,
        0,  258,    0,  258,    0,    0,  258,  259,    0,  259,
        0,    0,  259,  260,  260,  260,    0,  260,    0,    0,
      260,  261,    0,  261,    0,    0,  261,  262,    0,  262,
      262,    0,  262,  263,  263,    0,  263,    0,  263,  263,
      264,    0,  264,    0,  264,    0,    0,  264,  265,    0,
      265,    0,    0,  265,  266,  266,    0,  266,    0,  266,
      266,  267,    0,  267,    0,    0,  267,  268,  268,  268,
        0,    0,    0,    0,  268,  268,    0,    0,  268,  269,
        0,  269,    0,    0,  269,  270,  270,  270,    0,  270,

      270,  270,  270,  270,    0,    0,  270,  271,  271,    0,
      271,    0,  271,  271,  272,    0,    0,  272,    0,  272,
        0,    0,  272,  273,  273,  273,    0,    0,    0,  273,
      273,  273,    0,    0,  273,  274,    0,  274,    0,    0,
        0,  274,  274,  274,    0,    0,  274,  275,    0,  275,
        0,  275,    0,    0,  275,  276,    0,  276,    0,    0,
        0,  276,    0,  276,    0,    0,  276,  277,    0,  277,
        0,  277,    0,    0,  277,  278,    0,  278,    0,  278,
        0,    0,  278,  279,  279,  279,    0,  279,    0,    0,
      279,  280,    0,  280,    0,  280,    0,    0,  280,  281,

        0,  281,    0,    0,  281,  282,  282,  282,    0,  282,
      282,  282,  282,  282,    0,    0,  282,  283,    0,  283,
        0,    0,  283,  284,  284,  284,    0,    0,    0,  284,
      284,  284,    0,    0,  284,  285,    0,  285,    0,    0,
        0,  285,  285,  285,    0,    0,  285,  286,  286,  286,
        0,    0,    0,  286,  286,  286,    0,    0,  286,  287,
        0,  287,    0,    0,    0,  287,    0,  287,    0,    0,
      287,  288,    0,  288,    0,  288,    0,    0,  288,  289,
        0,  289,    0,    0,    0,  289,  289,  289,    0,    0,
      289,  290,    0,  290,    0,  290,    0,    0,  290,  291,

        0,  291,    0,    0,    0,  291,    0,  291,    0,    0,
      291,  292,    0,  292,    0,  292,    0,    0,  292,  293,
        0,  293,    0,  293,    0,    0,  293,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\analizador.l"
#define INITIAL 0
#line 2 ".\\analizador.l"

#undef yywrap
#define yywrap() 1 
#include <stdio.h>
#include <string.h>

void print(char *value, char *category);

#line 719 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 42 ".\\analizador.l"


#line 873 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 250 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1128 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 ".\\analizador.l"
{
    print(yytext, "ITERATION");
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 ".\\analizador.l"
{
    print(yytext, "CONTROL");
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 ".\\analizador.l"
{
    print(yytext, "ALLOCATION");
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 ".\\analizador.l"
{
    print(yytext, "FUNCTION");
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 60 ".\\analizador.l"
{
    print(yytext, "FUNCTION_CALL");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 ".\\analizador.l"
{
    print(yytext, "LOGICAL_OPERATION");
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 ".\\analizador.l"
{
    print(yytext, "COMPARISON_OPERATION");
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 73 ".\\analizador.l"
{
    print(yytext,"ARRAY");
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 ".\\analizador.l"
{
    print(yytext,"MATRIX");
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 ".\\analizador.l"
{
    print(yytext,"NUMBER");
} 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 ".\\analizador.l"
{
    print(yytext,"KEYWORD");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 90 ".\\analizador.l"
{
    print(yytext,"VARIABLE");
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 ".\\analizador.l"
{
    print(yytext,"GROUP");
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 ".\\analizador.l"
{
    print(yytext,"BLOK");
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 ".\\analizador.l"
{
    print(yytext,"COMPARISON_OPERATOR");
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 108 ".\\analizador.l"
{
    print(yytext,"ARITHMETIC_OPERATOR");
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 ".\\analizador.l"
{
    print(yytext,"LOGICAL_OPERATOR");
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 116 ".\\analizador.l"
{
    print(yytext,"ASSIGNMENT_OPERATOR");
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 122 ".\\analizador.l"
{
    print(yytext,"CHAIN");
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 127 ".\\analizador.l"
ECHO;
	YY_BREAK
#line 1094 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 250 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 250 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 249);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 127 ".\\analizador.l"

 
main()
{
 yylex();
}
 
//function that recives the lexical category and its value and prints it
void print(char *value, char *category)
{
    if(strcmp(value, ";") == 1)
    {
        printf("\n");
    }

    
    printf( "( %s , %s ) ", value, category );
}
