/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 48
#define YY_END_OF_BUFFER 49
static yyconst short int yy_accept[287] =
    {   0,
       45,   45,   49,   47,   46,   48,   45,   47,   24,    5,
       47,   38,   41,    6,   30,   35,    7,   40,   43,   40,
       47,   47,   47,   22,   22,   37,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   39,   47,   45,
       45,   40,    0,    5,    5,   42,    0,    0,    0,    0,
       35,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   25,    0,    0,    0,    0,    0,   10,    2,
        0,    0,    0,    0,    0,    0,    0,    0,   44,    0,
        0,   35,    0,   32,    0,   36,    0,    0,    0,    0,
       33,    0,    0,    0,    0,    9,    0,    4,    8,    0,

        0,    0,    0,   19,    0,    0,    0,   14,    3,    0,
        0,    0,   31,    0,    0,    0,    0,    0,   20,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   11,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   15,
        0,    0,   32,   32,   29,    0,    0,    0,    0,    0,
       34,    0,    0,   27,   27,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   36,   13,   21,    0,    0,
       12,   31,   31,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   36,   36,   16,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   27,    0,    0,   18,   36,    0,    0,    1,    0,
        0,    0,    0,    0,    0,    0,   17,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   28,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   26,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    1,    9,
       10,   11,   11,   12,   11,   13,   11,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,   16,
       17,   18,    1,    1,   19,   20,   20,   20,   20,   21,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   22,   20,   20,   20,   20,   20,   20,
       23,    1,   24,    1,   25,    1,   26,   27,   28,   29,

       30,   31,   27,   32,   33,   27,   27,   34,   35,   36,
       37,   38,   27,   39,   40,   41,   42,   27,   43,   27,
       27,   27,   44,   45,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    1,    2,    3,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    5,    1,    1,    6,    1,    7,    7,
        7,    7,    8,    8,    9,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,    1,    1,    1
    } ;

static yyconst short int yy_base[325] =
    {   0,
        0,    0,  670,  848,  848,  848,   43,  652,   44,  664,
      659,  848,  848,  848,  848,   47,  848,  647,  646,  644,
      633,   31,   29,   79,  848,  848,  632,   33,   37,   41,
       44,   42,   45,   47,   51,   64,   52,  848,  610,   84,
       91,  848,  100,    0,    0,  848,   60,  636,  642,  635,
        0,  103,  630,  104,  598,  615,    0,   62,   86,  100,
      614,  623,  848,  107,   97,   90,   98,   91,  130,  100,
      104,  101,  110,  119,  115,  122,  121,  123,  848,  145,
      159,  620,  162,  139,  163,  185,  132,  145,  181,  619,
      848,    0,  184,  157,  177,  159,  174,  604,  182,  205,

      612,  598,  175,  594,  187,  188,  190,  584,  581,  191,
      192,  214,  213,  215,  591,    0,  221,  208,  579,  230,
      225,  229,  242,  589,  233,    0,  246,  235,  217,  254,
        0,  276,  247,  562,  237,  133,  576,  238,  239,  573,
      583,    0,  582,  570,  848,  273,  281,  261,  254,  292,
      848,  276,  272,  270,  298,  568,  294,  575,  583,  576,
      305,  572,  310,  543,    0,  557,  561,  560,  544,  287,
      322,  568,  556,  326,  563,    0,  314,  309,  538,    0,
      329,  338,  552,  344,  341,  353,  375,  520,  526,  529,
      356,  531,  362,  359,  365,  313,  378,  304,  382,  384,

      397,  848,  530,    0,    0,  501,  419,  331,  514,  398,
      509,  339,  501,    0,  375,  385,    0,  350,  465,  460,
      448,  402,  431,  424,  389,    0,  461,  401,  848,  430,
      404,  395,  421,  441,  445,  385,  446,  443,  466,  503,
      399,  357,  317,  303,  467,  288,  481,  254,    0,  482,
      259,    0,  496,  480,  499,  848,  256,    0,  508,  512,
      229,  523,  520,  532,  554,  537,  487,  540,  178,    0,
      407,  429,  549,  554,  569,  136,    0,  521,  451,   77,
        0,  564,  479,  566,  507,  848,  597,  607,  611,  617,
      625,  631,  635,  641,  649,  655,  663,  669,  675,  682,

      688,  692,  698,  706,  712,  718,  724,  732,  738,  744,
      750,  757,  763,  771,  777,  785,  793,  799,  805,  811,
      819,  825,  831,  837
    } ;

static yyconst short int yy_def[325] =
    {   0,
      286,    1,  286,  286,  286,  286,  286,  286,  287,  288,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      289,  289,  289,  290,  286,  286,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  286,  286,  286,
      287,  286,  287,  288,  288,  286,   16,  286,  286,  286,
       16,  291,  286,  291,  286,  289,  292,  289,  289,  286,
      293,  294,  286,  293,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  286,  291,
      295,   47,  291,  286,  291,  292,  289,  289,  293,  286,
      286,  296,  286,  294,  297,  289,  289,  289,  289,  286,

      298,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  295,  286,  295,  286,  299,  300,  289,  289,  293,
      286,  296,  294,  286,  286,  301,  297,  286,  289,  289,
      302,  286,  298,  292,  289,  289,  289,  289,  289,  289,
      286,  303,  286,  299,  286,  286,  300,  294,  286,  286,
      286,  301,  289,  286,  286,  302,  132,  286,  286,  286,
      304,  286,  304,  286,  305,   86,  289,  289,  292,  289,
      289,  286,  303,  300,  286,  306,  286,  289,  286,  307,
      304,  308,  157,  304,  286,  304,  305,   86,   86,  289,
      286,  309,  300,  286,  306,  289,  286,  307,  308,  286,

      308,  286,  286,  310,   86,   86,  286,  309,  289,  286,
      311,  312,  286,  313,  286,  310,   86,  207,  286,  286,
      286,  314,  286,  314,  286,  315,  286,  311,  286,  286,
      312,  286,  313,  314,  316,  218,  314,  286,  314,  315,
      227,  286,  286,  286,  317,  286,  317,  286,  318,  312,
      286,  319,  316,  286,  316,  286,  286,  320,  317,  321,
      241,  317,  286,  317,  318,  312,  286,  319,  286,  322,
      286,  320,  321,  286,  321,  286,  323,  286,  322,  286,
      324,  286,  323,  286,  324,    0,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286
    } ;

static yyconst short int yy_nxt[895] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       22,   23,   24,   25,   26,   27,   27,   28,   27,   29,
       30,   27,   31,   27,   32,   33,   27,   34,   35,   36,
       27,   27,   37,   38,   39,   38,   40,   40,   41,   41,
       47,   48,   47,   57,   49,   57,   58,   57,   65,   50,
       51,   57,   52,   53,   54,   57,   57,   59,   57,   57,
       66,   57,  286,  286,   69,   57,   57,   67,   71,   70,
       74,   72,   68,   77,   78,   73,   57,   40,   57,   41,
      284,   55,   60,   75,   40,   87,   41,   61,   61,   61,

       61,   62,   63,  286,   76,   79,   83,   83,   83,   83,
       57,   89,   90,   60,   57,   57,   84,   84,   95,   80,
       80,   57,   57,   91,   57,   57,   99,   88,   57,   97,
       63,   92,  103,  100,   57,  100,   98,   96,  101,   57,
      102,  104,  105,   57,  106,   57,   57,   57,   83,  282,
       83,  115,   84,  110,   57,  108,   57,   57,   84,  107,
      109,  286,  112,  111,  112,   83,  286,   83,  286,   57,
      286,  118,  113,  168,  119,   84,  286,  129,  286,  286,
      127,  126,  127,   57,  120,  131,  120,  116,   47,   48,
       47,  278,   49,  117,   60,  123,  124,   93,   57,   57,

       52,   53,   54,  130,  135,  286,   57,  125,  100,   57,
      100,   57,   57,  101,   57,   57,   57,  112,  286,  112,
      286,  137,  136,  140,  139,  141,  113,  113,  286,   55,
      145,  138,   57,  120,  146,  120,   89,  119,  121,  142,
       89,   57,  261,   60,  150,  148,   95,  148,   91,  127,
      153,  127,   91,   92,  286,   93,  151,  154,   63,  155,
      286,   57,   57,   57,  148,  123,  148,  149,  171,  271,
      167,  165,  267,  155,   93,  155,  170,  125,   57,  157,
      158,  157,  145,  159,  174,  175,  146,  123,  160,  132,
      286,  161,  162,  163,  286,  177,   57,  177,  260,  125,

      126,  155,  179,  155,  259,  176,  286,  286,  184,  178,
      184,   57,  212,  184,   62,  184,  261,  177,  185,  177,
      164,  181,  190,  185,  260,  191,  181,  191,  180,  193,
      192,  193,  184,   57,  184,  286,   62,   57,  209,  146,
      196,  199,  185,  199,  286,  286,   57,  184,  229,  184,
      202,  200,  230,  203,  185,  226,  286,  185,  286,  191,
      286,  191,  286,  286,  192,  193,  286,  193,  145,  286,
      174,  286,  194,  259,  145,  146,  174,  204,  157,  158,
      157,  210,  159,  210,  202,  199,  211,  199,  215,  176,
      161,  162,  163,  202,  202,  200,  213,  200,  236,  165,

      286,  210,  286,  210,  202,  237,  211,  237,  232,  204,
      286,  286,  286,  286,  286,  238,  256,  286,  234,  164,
      271,  214,  218,  219,  218,  249,  220,  237,  252,  237,
      202,  221,  207,  235,  222,  223,  224,  238,  256,  229,
      234,  250,  251,  230,  237,  214,  237,  234,  253,  237,
      253,  237,  256,  258,  238,  257,  238,  286,  254,  238,
      256,  236,  286,  225,  241,  242,  241,  235,  243,  286,
      262,  286,  262,  244,  227,  270,  245,  246,  247,  286,
      263,  234,  286,  259,  262,  266,  262,  266,  202,  256,
      258,  286,  269,  254,  263,  230,  229,  259,  250,  253,

      267,  253,  286,  277,  286,  248,  218,  219,  218,  254,
      220,  262,  286,  262,  232,  273,  202,  273,  222,  223,
      224,  263,  227,  270,  286,  274,  262,  226,  262,  202,
      256,  281,  276,  263,  278,  286,  263,  286,   57,  286,
      266,  217,  266,  215,  207,  286,  286,  225,  286,  229,
      230,  250,  273,   57,  273,  206,  277,  241,  242,  241,
      205,  243,  274,  202,  252,  183,  280,  274,  197,  245,
      246,  247,  286,  202,  286,  202,  194,  282,  249,  284,
      142,  172,  286,  189,   57,   57,  188,  182,  181,  183,
      182,  181,  180,  281,  116,  143,  172,   57,  248,   43,

      169,  166,  149,   57,  143,   57,   43,   44,   57,   44,
       44,   44,   44,   44,   44,   44,   44,   56,   57,   56,
       56,   64,  134,   64,   64,  132,   64,   85,   57,   85,
       85,   85,  121,   82,   85,   86,   93,   86,   92,   57,
       86,   61,   81,   61,   61,   94,   80,   94,   82,   81,
       94,  114,   80,  114,   46,  114,   57,   57,  114,  122,
       42,  122,   42,   42,  122,  128,   46,   45,   42,  286,
      286,  286,  128,  133,  286,  133,  286,  286,  133,  144,
      286,  144,  286,  286,  144,  147,  147,  286,  147,  286,
      286,  147,  152,  286,  152,  286,  286,  152,  156,  286,

      286,  156,  173,  286,  173,  286,  286,  173,  186,  286,
      186,  186,  186,  286,  286,  186,  187,  286,  187,  286,
      286,  187,  195,  286,  195,  286,  286,  195,  198,  286,
      198,  286,  286,  198,  201,  286,  201,  286,  201,  286,
      286,  201,  208,  286,  208,  286,  286,  208,  216,  286,
      216,  286,  286,  216,  228,  286,  228,  286,  286,  228,
      231,  231,  286,  231,  286,  286,  231,  233,  286,  233,
      286,  286,  233,  239,  286,  239,  239,  239,  286,  286,
      239,  240,  286,  240,  286,  286,  240,  255,  286,  255,
      286,  255,  286,  286,  255,  264,  286,  264,  264,  264,

      286,  286,  264,  265,  286,  265,  286,  286,  265,  268,
      286,  268,  286,  286,  268,  272,  286,  272,  286,  286,
      272,  275,  286,  275,  286,  275,  286,  286,  275,  279,
      286,  279,  286,  286,  279,  283,  286,  283,  286,  286,
      283,  285,  286,  285,  286,  286,  285,    3,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286

    } ;

static yyconst short int yy_chk[895] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    7,    9,    7,    9,
       16,   16,   16,   23,   16,   22,   22,   28,   28,   16,
       16,   29,   16,   16,   16,   30,   32,   23,   31,   33,
       29,   34,   47,   47,   31,   35,   37,   30,   32,   31,
       35,   33,   30,   37,   37,   34,   58,   40,   36,   40,
      280,   16,   24,   36,   41,   58,   41,   24,   24,   24,

       24,   24,   24,   43,   36,   43,   52,   54,   52,   54,
       59,   60,   60,   60,   66,   68,   52,   54,   64,   52,
       54,   65,   67,   60,   70,   72,   68,   59,   71,   66,
       64,   64,   71,   69,   73,   69,   67,   65,   69,   75,
       70,   72,   73,   74,   74,   77,   76,   78,   80,  276,
       80,   84,   84,   77,   69,   75,   87,  136,   80,   74,
       76,   80,   81,   78,   81,   83,   85,   83,   85,   88,
       94,   87,   81,  136,   88,   83,   85,   96,   83,   85,
       95,   94,   95,   96,   89,   99,   89,   85,   86,   86,
       86,  269,   86,   86,   89,   93,   93,   93,   97,  103,

       86,   86,   86,   97,  103,   89,   99,   93,  100,   86,
      100,  105,  106,  100,  107,  110,  111,  112,  114,  112,
      114,  106,  105,  111,  110,  113,  113,  112,  114,   86,
      117,  107,  118,  120,  117,  120,  121,  118,  121,  114,
      122,  129,  261,  120,  125,  123,  128,  123,  121,  127,
      129,  127,  122,  122,  120,  123,  125,  130,  128,  130,
      133,  135,  138,  139,  148,  149,  148,  149,  139,  257,
      135,  133,  251,  154,  148,  154,  138,  149,  130,  132,
      132,  132,  146,  132,  146,  146,  146,  152,  132,  132,
      147,  132,  132,  132,  147,  150,  153,  150,  248,  152,

      152,  155,  154,  155,  246,  147,  157,  157,  161,  153,
      161,  170,  198,  163,  150,  163,  244,  177,  161,  177,
      132,  161,  170,  163,  243,  171,  163,  171,  198,  174,
      171,  174,  181,  178,  181,  174,  177,  196,  196,  174,
      178,  182,  181,  182,  208,  181,  171,  184,  212,  184,
      185,  182,  212,  185,  185,  208,  186,  184,  186,  191,
      184,  191,  218,  218,  191,  193,  186,  193,  194,  186,
      194,  193,  194,  242,  195,  193,  195,  186,  187,  187,
      187,  197,  187,  197,  215,  199,  197,  199,  215,  195,
      187,  187,  187,  200,  216,  199,  200,  200,  236,  187,

      201,  210,  201,  210,  232,  222,  210,  222,  232,  216,
      201,  241,  241,  231,  228,  222,  271,  231,  222,  187,
      271,  201,  207,  207,  207,  228,  207,  224,  231,  224,
      233,  207,  207,  225,  207,  207,  207,  224,  272,  230,
      224,  230,  230,  230,  234,  233,  234,  223,  235,  237,
      235,  237,  238,  272,  234,  238,  238,  234,  235,  237,
      279,  221,  237,  207,  227,  227,  227,  220,  227,  239,
      245,  239,  245,  227,  227,  279,  227,  227,  227,  239,
      245,  219,  239,  245,  247,  250,  247,  250,  283,  254,
      239,  250,  254,  254,  247,  250,  267,  247,  267,  253,

      267,  253,  255,  283,  255,  227,  240,  240,  240,  253,
      240,  259,  255,  259,  213,  260,  285,  260,  240,  240,
      240,  259,  211,  255,  259,  260,  262,  240,  262,  263,
      278,  285,  263,  263,  278,  264,  262,  264,  209,  262,
      266,  206,  266,  203,  192,  264,  266,  240,  264,  268,
      266,  268,  273,  190,  273,  189,  264,  265,  265,  265,
      188,  265,  273,  274,  268,  183,  274,  274,  179,  265,
      265,  265,  275,  282,  275,  284,  175,  282,  265,  284,
      173,  172,  275,  169,  168,  167,  166,  164,  162,  160,
      159,  158,  156,  275,  144,  143,  141,  140,  265,  287,

      137,  134,  124,  119,  115,  109,  287,  288,  108,  288,
      288,  288,  288,  288,  288,  288,  288,  289,  104,  289,
      289,  290,  102,  290,  290,  101,  290,  291,   98,  291,
      291,  291,   90,   82,  291,  292,   62,  292,   61,   56,
      292,  293,   55,  293,  293,  294,   53,  294,   50,   49,
      294,  295,   48,  295,   39,  295,   27,   21,  295,  296,
       20,  296,   19,   18,  296,  297,   11,   10,    8,    3,
        0,    0,  297,  298,    0,  298,    0,    0,  298,  299,
        0,  299,    0,    0,  299,  300,  300,    0,  300,    0,
        0,  300,  301,    0,  301,    0,    0,  301,  302,    0,

        0,  302,  303,    0,  303,    0,    0,  303,  304,    0,
      304,  304,  304,    0,    0,  304,  305,    0,  305,    0,
        0,  305,  306,    0,  306,    0,    0,  306,  307,    0,
      307,    0,    0,  307,  308,    0,  308,    0,  308,    0,
        0,  308,  309,    0,  309,    0,    0,  309,  310,    0,
      310,    0,    0,  310,  311,    0,  311,    0,    0,  311,
      312,  312,    0,  312,    0,    0,  312,  313,    0,  313,
        0,    0,  313,  314,    0,  314,  314,  314,    0,    0,
      314,  315,    0,  315,    0,    0,  315,  316,    0,  316,
        0,  316,    0,    0,  316,  317,    0,  317,  317,  317,

        0,    0,  317,  318,    0,  318,    0,    0,  318,  319,
        0,  319,    0,    0,  319,  320,    0,  320,    0,    0,
      320,  321,    0,  321,    0,  321,    0,    0,  321,  322,
        0,  322,    0,    0,  322,  323,    0,  323,    0,    0,
      323,  324,    0,  324,    0,    0,  324,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\analizador.l"
#define INITIAL 0
#line 2 ".\\analizador.l"

#define yywrap() 1
#include <stdio.h>
#include <stdlib.h>
#include <stdio.h>
#include <conio.h>
#include <string.h>
FILE *yyin;

void print(char *value, char *category);

/* KEYWORDS */
/*ALLOCATION              {VARIABLE}{space}={space}{data_type} */
#line 677 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 76 ".\\analizador.l"

#line 830 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 287 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 848 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 77 ".\\analizador.l"
{
    print(yytext, "CAT_ALPHA");
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 ".\\analizador.l"
{
    print(yytext, "IN");
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 85 ".\\analizador.l"
{
    print(yytext, "STRING");
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 89 ".\\analizador.l"
{
    print(yytext, "FOR");
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 93 ".\\analizador.l"
{
    print(yytext, "COMMENT");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 97 ".\\analizador.l"
{
    print(yytext, "COMA");
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 101 ".\\analizador.l"
{
    print(yytext, "END_OF_STATEMENT");
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 ".\\analizador.l"
{
    print(yytext, "FUN_KEYWORD");
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 109 ".\\analizador.l"
{
    print(yytext, "CAT_KEYWORD");
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 113 ".\\analizador.l"
{
    print(yytext, "IF_KEYWORD");
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 117 ".\\analizador.l"
{
    print(yytext, "ELSE_KEYWORD");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 121 ".\\analizador.l"
{
    print(yytext, "WHILE_KEYWORD");
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 125 ".\\analizador.l"
{
    print(yytext, "IF_KEYWORD");
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 129 ".\\analizador.l"
{
    print(yytext, "SET_KEYWORD");
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 133 ".\\analizador.l"
{
    print(yytext, "WITH_KEYWORD");
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 137 ".\\analizador.l"
{
    print(yytext, "RETURN_KEYWORD");
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 141 ".\\analizador.l"
{
    print(yytext, "REAL_SET_KEYWORD");
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 145 ".\\analizador.l"
{
    print(yytext, "INT_SET_KEYWORD");
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 149 ".\\analizador.l"
{
    print(yytext, "NOT_KEYWORD");
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 153 ".\\analizador.l"
{
    print(yytext, "BOOLEAN");
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 157 ".\\analizador.l"
{
    print(yytext, "PRINT");
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 161 ".\\analizador.l"
{
    print(yytext, "ARRAY_SYMBOL");
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 165 ".\\analizador.l"
{
    print(yytext, "SYMBOL");
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 169 ".\\analizador.l"
{
    print(yytext, "CHAIN_SYMBOL");
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 173 ".\\analizador.l"
{
    print(yytext, "CATEGORY_ALPHABET");
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 177 ".\\analizador.l"
{
    print(yytext, "ITERATION");
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 181 ".\\analizador.l"
{
    print(yytext, "CONTROL");
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 185 ".\\analizador.l"
{
    print(yytext, "FUNCTION");
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 189 ".\\analizador.l"
{
    print(yytext, "FUNCTION_CALL");
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 193 ".\\analizador.l"
{
    print(yytext, "VARIABLE_FUNCTION");
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 197 ".\\analizador.l"
{
    print(yytext, "LOGICAL_OPERATION");
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 201 ".\\analizador.l"
{
    print(yytext, "COMPARISON_OPERATION");
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 205 ".\\analizador.l"
{
    print(yytext,"ARRAY");
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 209 ".\\analizador.l"
{
    print(yytext,"MATRIX");
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 213 ".\\analizador.l"
{
    print(yytext,"NUMBER");
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 217 ".\\analizador.l"
{
    print(yytext,"VARIABLE");
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 221 ".\\analizador.l"
{
    print(yytext, "VARIABLE_MID_SYMBOL");
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 225 ".\\analizador.l"
{
    print(yytext,"GROUP");
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 229 ".\\analizador.l"
{
    print(yytext,"BLOCK");
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 233 ".\\analizador.l"
{
    print(yytext,"COMPARISON_OPERATOR");
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 237 ".\\analizador.l"
{
    print(yytext,"ARITHMETIC_OPERATOR");
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 241 ".\\analizador.l"
{
    print(yytext,"LOGICAL_OPERATOR");
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 245 ".\\analizador.l"
{
    print(yytext,"ASSIGNMENT_OPERATOR");
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 249 ".\\analizador.l"
{
    print(yytext,"CHAIN");
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 253 ".\\analizador.l"
{

}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 257 ".\\analizador.l"
{
    
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 261 ".\\analizador.l"
{
    printf("\nCaracter invalido: %s\n", yytext);
    exit(1);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 266 ".\\analizador.l"
ECHO;
	YY_BREAK
#line 1248 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 287 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 287 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 286);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 266 ".\\analizador.l"

/*
int main()
{
    yylex();
}
*/


int main (int argc, char *argv[]){
    char file_name[20];
    printf("Inserte el nombre del archivo a ejecutar (con .txt): \n");
    scanf("%s", file_name);
    argv[1] = file_name;
    if ((yyin = fopen(argv[1], "rt")) == NULL) {
        printf("\nNo se pudo leer el archivo: %s\n", argv[1]);
        return 1;
    } else {
        printf("\nEl archivo %s se abrio correctamente\n", argv[1]);
        yylex();
    }
    printf("\nLectura finalizada.");
    fclose(yyin);
    return 0;
}


 
//function that recives the lexical category and its value and prints it
void print(char *value, char *category)
{   
    printf("\n( %s , %s ) ", value, category );
}